title: Welcome!
author: Rachel Chong 
email: raydahee@gmail.com 
description: > # this means to ignore newlines until "baseurl:"
  Hi my name is Rachel Chong and welcome to my first website! I hope this is cool.

# social links
instagram_username: rachel._.chong 
github_username:  rachongg

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima 
